#!/usr/bin/env bash

scrape_soundcloud(){
  python $SCRIPT_DIR/sc_scrape.py $1
}
scrape_youtube(){
  python $SCRIPT_DIR/yt_scrape.py $1
}
update_directory(){
  echo "enter the name of the directory you want to store your music"
  read -r -e directory
  touch "$config"
  sed -i '/directory/d' $config
  echo "directory: $directory" >> "$config"
}
update_account(){
  echo "enter your $1 account url"
  read -r account_url
  echo "$1: $account_url" >> "$config"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
config="$HOME/.config/music_mover.txt"


echo "Change download directory? (y/n)"
read -r change
if ! [ -f "$config" ] || ! grep "directory" $config || [[ $change == "y" ]]; then
  update_directory
fi
pip install -r "$SCRIPT_DIR/requirements.txt"
platform=""
while  [[ "$platform" != "s" ]] && [[ "$platform" != "y" ]]; do
  echo "downloading from (y)outube or (s)oundcloud?"
  read -r platform
done
if [[ "$platform" == "s" ]]; then 
  platform="soundcloud"
else 
  platform="youtube"
fi
if ! grep $platform "$config"; then
  update_account "$platform"
fi

url=$(grep $platform "$config" | sed "s/$platform: //")

if  [[ $platform == "soundcloud" ]];then
  playlists=$(scrape_soundcloud "$url")
else
  playlists=$(scrape_youtube "$url")
fi


declare -a playlists_array
read -r -a playlists_array <<< "$playlists"

i=0
declare -a playlists_link_array
declare -a playlists_name_array
for playlist in "${playlists_array[@]}"; do 
  if ((i%2==0)); then
    playlists_name_array+=($playlist)
    index=$(($i/2+1))
    echo $index: "$playlist"
  else
    playlists_link_array+=($playlist)
  fi
  ((i++))
done

echo "which playlist would you like to download: "
read -r input
input=$(($input-1))
download_directory=$(grep "directory" "$config" | sed 's/directory: //')
download_directory+="/"
download_directory+=${playlists_name_array[$input]}
echo $download_directory
mkdir $download_directory
echo ${playlists_link_array[@]}
yt-dlp -o "%(playlist_index)s - %(title)s.%(ext)s" -P "$download_directory" -x --audio-format mp3 "${playlists_link_array[$input]}" 


